### ISSUE TITLE
Fix "Unhandled promise rejection" error

### ISSUE THREAD

**Issue by enricmartos** [enricmartos/learn-and-fun#1]
*Description*
After signing in, Node.js is termined due to a "Unhandled promise rejection" error.

`(node:8360) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.rename (fs.js:571:14)
    at C:\Users\enrik\Documents\learn-and-fun\learn-and-fun\app.js:89:8
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

*Steps to reproduce*

- Fill the sign up form and click Sign in
- Check that the app reaches a timeout and stops

*Actual result*
The app reaches a timeout and stops due to unhandled promises.

*Expected result*
After handling promises, all the processes should work properly.

**Comment by enricmartos** [comment]
This bug affects all the file uploads (profile images and lesson images). _fs.rename(...)_ requires a third parameter, which is a callback function to be invoked when the operation completes.  

Source: [fs.rename(oldPath, newPath, callback) (Node docs)](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback)

After adding this callback as a third parameter all the file uploads work as expected.
